### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by pwilkowski** [h2zero/n-able-Arduino#24]
Hello

I have a question regarding license, is it possible to use in in commercial product? If so, what are the terms? Dynamic linking would be hard as part of firmware that is pretty much core of application.

**Comment by h2zero** [comment]
It's usable commercially just like any other Arduino core. Contribute back any modifications made and indicate them in your distribution is most of what's required by the license. Your application code can remain proprietary if you provide the object files for linking to this library.
