### ISSUE TITLE
Fails to compile on Win11

### ISSUE THREAD

**Issue by Q-point** [h2zero/n-able-Arduino#26]
When compiling a simple blinky fails with : 

echo Not building DFU package
exit status -1073741515
Error compiling for board Nordic nRF52832DK (PCA10040).

When compiling with NIM-BLE app fails with : 

exit status 0xc0000135

Compilation error: exit status 0xc0000135

**Comment by h2zero** [comment]
This appears to be an Arduino IDE error in windows and not an error with this library.

**Comment by Q-point** [comment]
I moved over to platform IO and it works out of the box there. The above issue is present on both 1.8 and 2.x Arduino releases.
