### ISSUE TITLE
nRF52810 support?

### ISSUE THREAD

**Issue by positron96** [h2zero/n-able-Arduino#45]
Hello. Does this core support nRF52810 MCU? I am doing a custom board with that MCU, and looking for PlatformIO framework to use.

I don't see it mentioned in the list ofsupported boards, but I understand that the compiler, tools and libraries are the same as for other nRF52 MCUs. How extensive will the changes needed to compile for the that MCU be?

**Comment by h2zero** [comment]
It's no too extensive, would need to pull in the startup code from nrfx and adjust the linker, and a board variant.

**Comment by positron96** [comment]
Would you be interested in a PR if I make it work for me?

**Comment by h2zero** [comment]
I would love it if you did :). If you want to start I can help as well. Just make a change and open a PR that we can both add to.
