### ISSUE TITLE
nrf52810 Compilation Error Resulting From Typo in boards.txt

### ISSUE THREAD

**Issue by jackb60** [h2zero/n-able-Arduino#50]
As the library is right now, I get `#error "Device must be defined. See nrf.h."`

In boards.txt, I believe line 1977

 `Generic_nRF52810.build.extra_flags=-DNRF52_SERIES -DnRF52810_XXAA {bootloader.flags} -DCONFIG_NIMBLE_CPP_LOG_LEVEL={build.cpp_debug} {build.nimble_flags}`

should be changed to 

 `Generic_nRF52810.build.extra_flags=-DNRF52_SERIES -DNRF52810_XXAA {bootloader.flags} -DCONFIG_NIMBLE_CPP_LOG_LEVEL={build.cpp_debug} {build.nimble_flags}`

**Comment by h2zero** [comment]
Thanks! That definitely looks like the issue 🙂. Will be fixed shortly.
