### ISSUE TITLE
NRF52810 Notify Limited By CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT

### ISSUE THREAD

**Issue by jackb60** [h2zero/n-able-Arduino#53]
I am using a NRF52810 with `<NimBLEDevice.h>` and when an attempt is made to notify with a characteristic length of greater than 339 bytes, the central does not recieve the data and onStatus indicates a return code of 6 (operation failed due to resource exhaustion). That may also be the case with other operations but I only tested notify.

I was able to get it working by changing line 13 in nrf52810_nimconfig.h from

`#define CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT (8)` to 
`#define CONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT (12)`

**Comment by h2zero** [comment]
That's exactly the correct solution 👍. Please see my comment [here](https://github.com/h2zero/n-able-Arduino/issues/51#issuecomment-2209671294) for a per sketch configuration solution to this.

Per my comment there you would add this: `-DCONFIG_BT_NIMBLE_MSYS1_BLOCK_COUNT=12` to the `build_opt.h` file
